# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-03 13:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='openings',
            new_name='opening',
        ),
    ]
