# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-04 21:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0005_auto_20160704_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='no_openings',
            field=models.IntegerField(default=0),
        ),
    ]
