# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-04 22:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0006_company_no_openings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='opening',
            field=models.BooleanField(default=False),
        ),
    ]
